# Generated by Django 4.2.3 on 2023-07-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('D', 'Delivered'), ('C', 'Cancelled')], default='P', max_length=1),
        ),
    ]
