# Generated by Django 4.2.3 on 2023-07-11 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_payment_status_order_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
