# Generated by Django 4.1.4 on 2023-07-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_checkout_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
