# Generated by Django 4.1.4 on 2023-07-29 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_purchase_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stripe_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stripe_price_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stripe_product_id',
        ),
    ]
